update ssh example
explicitly invoke /bin/sh in the example.
Without this, we get:

>>> io = session.process('sh', env={"PS1":""})
[x] Starting remote process None on bandit.labs.overthewire.org
[ERROR] b"b'sh' is not executable or does not exist in $PATH: [b'']"
[-] Starting remote process None on bandit.labs.overthewire.org: Failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/crd/pwntools/lib64/python3.12/site-packages/pwnlib/tubes/ssh.py", line 977, in process
    self.error("%r" % error_message)
  File "/home/crd/pwntools/lib64/python3.12/site-packages/pwnlib/log.py", line 439, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: b"b'sh' is not executable or does not exist in $PATH: [b'']"